Fixing jf dockerscan command panic
jfrog/jfrog-cli-security pull request #154
Opened 2024-08-24 20:01 UTC by dortam888

… docker scan

- [ ] The pull request is targeting the `dev` branch.
- [ ] The code has been validated to compile successfully by running `go vet ./...`.
- [ ] The code has been formatted properly using `go fmt ./...`.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-security/actions/workflows/analysis.yml) passed.
- [ ] All [tests](https://github.com/jfrog/jfrog-cli-security/actions/workflows/test.yml) have passed. If this feature is not already covered by the tests, new tests have been added.
- [ ] All changes are detailed at the description. if not already covered at [JFrog Documentation](https://github.com/jfrog/documentation), new documentation have been added.

-----

the JFrog cli might offer jf dockerscan as a command as its appearing on the command list but it has no Action function.
Added an action function to return the same output as jf docker scan would return.

2024-08-26 11:33 UTC, attiasas requested changes
what is the panic? please add to the description.
I could not replicate the issue.
Also this is a hidden command that inject and shows the `HELP` for `jf docker scan` it is not a command on its own.

2024-08-26 12:00 UTC, dortam888 commented
@attiasas When running jf dockerscan even if by accident we're getting panic instead of handling.
We have many hidden commands but with action function. 
Either jf dockerscan will do the same as jf docker scan (that's what I implemented) 
Or we should output something like:
'jf dockerscan' is not a jf command. See --help
The most similar command is:
	jf docker scan 

Take in account that if we're running something close to jf dockerscan it will output:
'jf dockersca' is not a jf command. See --help
The most similar command is:
	jf dockerscan
And I can't change it since its reading it as a command

2024-09-04 09:26 UTC, attiasas commented
@dortam888 , As discussed, this needs to be behave similar to `dockerpullhelp` in the CLI project

2024-10-22 08:25 UTC, eranturgeman commented on cli/docs/scan/dockerscan/help.go
> +func GetArguments() string {
return this as []components.Argument as we do so for all other commands. we don't want to create a different types just for one single command

2024-11-03 13:19 UTC, closed without merging